/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 45
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_blank_line_token1 = 1,
  anon_sym_POUND_POUND_POUND = 2,
  aux_sym_request_separator_token1 = 3,
  aux_sym_method_line_token1 = 4,
  anon_sym_GET = 5,
  anon_sym_POST = 6,
  anon_sym_PUT = 7,
  anon_sym_DELETE = 8,
  anon_sym_PATCH = 9,
  anon_sym_OPTIONS = 10,
  anon_sym_HEAD = 11,
  anon_sym_TRACE = 12,
  anon_sym_CONNECT = 13,
  sym_target = 14,
  sym_http_version = 15,
  anon_sym_COLON = 16,
  sym_header_name = 17,
  sym_header_value = 18,
  aux_sym_body_content_token1 = 19,
  anon_sym_POUND = 20,
  aux_sym_body_content_token2 = 21,
  anon_sym_POUND_POUND = 22,
  anon_sym_SLASH_SLASH = 23,
  sym_source_file = 24,
  sym_blank_line = 25,
  sym_request_separator = 26,
  sym_request = 27,
  sym_method_line = 28,
  sym_method = 29,
  sym_headers = 30,
  sym_header = 31,
  sym_body = 32,
  sym_body_content = 33,
  sym_comment = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_headers_repeat1 = 36,
  aux_sym_body_content_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_blank_line_token1] = "blank_line_token1",
  [anon_sym_POUND_POUND_POUND] = "###",
  [aux_sym_request_separator_token1] = "request_separator_token1",
  [aux_sym_method_line_token1] = "method_line_token1",
  [anon_sym_GET] = "GET",
  [anon_sym_POST] = "POST",
  [anon_sym_PUT] = "PUT",
  [anon_sym_DELETE] = "DELETE",
  [anon_sym_PATCH] = "PATCH",
  [anon_sym_OPTIONS] = "OPTIONS",
  [anon_sym_HEAD] = "HEAD",
  [anon_sym_TRACE] = "TRACE",
  [anon_sym_CONNECT] = "CONNECT",
  [sym_target] = "target",
  [sym_http_version] = "http_version",
  [anon_sym_COLON] = ":",
  [sym_header_name] = "header_name",
  [sym_header_value] = "header_value",
  [aux_sym_body_content_token1] = "body_content_token1",
  [anon_sym_POUND] = "#",
  [aux_sym_body_content_token2] = "body_content_token2",
  [anon_sym_POUND_POUND] = "##",
  [anon_sym_SLASH_SLASH] = "//",
  [sym_source_file] = "source_file",
  [sym_blank_line] = "blank_line",
  [sym_request_separator] = "request_separator",
  [sym_request] = "request",
  [sym_method_line] = "method_line",
  [sym_method] = "method",
  [sym_headers] = "headers",
  [sym_header] = "header",
  [sym_body] = "body",
  [sym_body_content] = "body_content",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_headers_repeat1] = "headers_repeat1",
  [aux_sym_body_content_repeat1] = "body_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_blank_line_token1] = aux_sym_blank_line_token1,
  [anon_sym_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND,
  [aux_sym_request_separator_token1] = aux_sym_request_separator_token1,
  [aux_sym_method_line_token1] = aux_sym_method_line_token1,
  [anon_sym_GET] = anon_sym_GET,
  [anon_sym_POST] = anon_sym_POST,
  [anon_sym_PUT] = anon_sym_PUT,
  [anon_sym_DELETE] = anon_sym_DELETE,
  [anon_sym_PATCH] = anon_sym_PATCH,
  [anon_sym_OPTIONS] = anon_sym_OPTIONS,
  [anon_sym_HEAD] = anon_sym_HEAD,
  [anon_sym_TRACE] = anon_sym_TRACE,
  [anon_sym_CONNECT] = anon_sym_CONNECT,
  [sym_target] = sym_target,
  [sym_http_version] = sym_http_version,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_header_name] = sym_header_name,
  [sym_header_value] = sym_header_value,
  [aux_sym_body_content_token1] = aux_sym_body_content_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_body_content_token2] = aux_sym_body_content_token2,
  [anon_sym_POUND_POUND] = anon_sym_POUND_POUND,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [sym_source_file] = sym_source_file,
  [sym_blank_line] = sym_blank_line,
  [sym_request_separator] = sym_request_separator,
  [sym_request] = sym_request,
  [sym_method_line] = sym_method_line,
  [sym_method] = sym_method,
  [sym_headers] = sym_headers,
  [sym_header] = sym_header,
  [sym_body] = sym_body,
  [sym_body_content] = sym_body_content,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_headers_repeat1] = aux_sym_headers_repeat1,
  [aux_sym_body_content_repeat1] = aux_sym_body_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_blank_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_request_separator_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_method_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POST] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PUT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DELETE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PATCH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OPTIONS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HEAD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CONNECT] = {
    .visible = true,
    .named = false,
  },
  [sym_target] = {
    .visible = true,
    .named = true,
  },
  [sym_http_version] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_header_name] = {
    .visible = true,
    .named = true,
  },
  [sym_header_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_body_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_body_content_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_request_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_request] = {
    .visible = true,
    .named = true,
  },
  [sym_method_line] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_headers] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_body_content] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_headers_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_method = 2,
  field_name = 3,
  field_url = 4,
  field_value = 5,
  field_version = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_method] = "method",
  [field_name] = "name",
  [field_url] = "url",
  [field_value] = "value",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
  [1] =
    {field_name, 0},
  [2] =
    {field_method, 0},
    {field_url, 2},
  [4] =
    {field_name, 0},
    {field_value, 2},
  [6] =
    {field_name, 0},
    {field_value, 3},
  [8] =
    {field_method, 0},
    {field_url, 2},
    {field_version, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '\n', 20,
        '\r', 1,
        '#', 124,
        '/', 6,
        ':', 46,
        'C', 69,
        'D', 55,
        'G', 56,
        'H', 57,
        'O', 72,
        'P', 50,
        'T', 73,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(126);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(122);
      if (lookahead != 0) ADVANCE(123);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(130);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'H') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      if (lookahead == 'P') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'T') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'T') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(43);
      END_STATE();
    case 13:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(127);
      END_STATE();
    case 17:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '\n', 20,
        '\r', 1,
        '#', 124,
        '/', 88,
        'C', 109,
        'D', 96,
        'G', 97,
        'H', 98,
        'O', 111,
        'P', 91,
        'T', 112,
        '\t', 87,
        ' ', 87,
      );
      if (lookahead != 0) ADVANCE(123);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '\n', 20,
        '\r', 1,
        '#', 125,
        '/', 6,
        'C', 69,
        'D', 55,
        'G', 56,
        'H', 58,
        'O', 72,
        'P', 50,
        'T', 73,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_blank_line_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_request_separator_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_request_separator_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_method_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GET);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GET);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_POST);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_POST);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PUT);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PUT);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DELETE);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DELETE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PATCH);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PATCH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_OPTIONS);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_OPTIONS);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_HEAD);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_HEAD);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_TRACE);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_TRACE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_CONNECT);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_CONNECT);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_target);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_http_version);
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_http_version);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'A') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'A') ADVANCE(52);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'A') ADVANCE(78);
      if (lookahead == 'O') ADVANCE(75);
      if (lookahead == 'U') ADVANCE(79);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'C') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'C') ADVANCE(59);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'C') ADVANCE(81);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'D') ADVANCE(37);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(76);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(48);
      if (lookahead == 'T') ADVANCE(82);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(48);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(39);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(53);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(83);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'H') ADVANCE(33);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'I') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'L') ADVANCE(62);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'N') ADVANCE(68);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'N') ADVANCE(74);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'N') ADVANCE(61);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'O') ADVANCE(66);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'O') ADVANCE(67);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'P') ADVANCE(47);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'P') ADVANCE(77);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'R') ADVANCE(49);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'S') ADVANCE(35);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'S') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(25);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(64);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(29);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(27);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(71);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_header_value);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_header_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      ADVANCE_MAP(
        '/', 88,
        'C', 109,
        'D', 96,
        'G', 97,
        'H', 98,
        'O', 111,
        'P', 91,
        'T', 112,
        '\t', 87,
        ' ', 87,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == '/') ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'A') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'A') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'A') ADVANCE(117);
      if (lookahead == 'O') ADVANCE(114);
      if (lookahead == 'U') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'C') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'C') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'C') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'D') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'E') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'E') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'E') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'E') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'E') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'E') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'E') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'H') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'I') ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'L') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'N') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'N') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'N') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'O') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'O') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'P') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'R') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'S') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'S') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'T') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'T') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'T') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'T') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'T') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'T') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == 'T') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(122);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym_body_content_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(129);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(5);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(128);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_body_content_token2);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      if (lookahead == '#') ADVANCE(21);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#') ADVANCE(123);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 18},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 17},
  [7] = {.lex_state = 18},
  [8] = {.lex_state = 17},
  [9] = {.lex_state = 17},
  [10] = {.lex_state = 17},
  [11] = {.lex_state = 18},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 18},
  [15] = {.lex_state = 18},
  [16] = {.lex_state = 18},
  [17] = {.lex_state = 18},
  [18] = {.lex_state = 18},
  [19] = {.lex_state = 18},
  [20] = {.lex_state = 18},
  [21] = {.lex_state = 18},
  [22] = {.lex_state = 18},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 22},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 22},
  [44] = {.lex_state = 22},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_blank_line_token1] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(1),
    [anon_sym_GET] = ACTIONS(1),
    [anon_sym_POST] = ACTIONS(1),
    [anon_sym_PUT] = ACTIONS(1),
    [anon_sym_DELETE] = ACTIONS(1),
    [anon_sym_PATCH] = ACTIONS(1),
    [anon_sym_OPTIONS] = ACTIONS(1),
    [anon_sym_HEAD] = ACTIONS(1),
    [anon_sym_TRACE] = ACTIONS(1),
    [anon_sym_CONNECT] = ACTIONS(1),
    [sym_http_version] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_header_name] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(30),
    [sym_blank_line] = STATE(2),
    [sym_request_separator] = STATE(2),
    [sym_request] = STATE(2),
    [sym_method_line] = STATE(4),
    [sym_method] = STATE(29),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_blank_line_token1] = ACTIONS(5),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(7),
    [anon_sym_GET] = ACTIONS(9),
    [anon_sym_POST] = ACTIONS(9),
    [anon_sym_PUT] = ACTIONS(9),
    [anon_sym_DELETE] = ACTIONS(9),
    [anon_sym_PATCH] = ACTIONS(9),
    [anon_sym_OPTIONS] = ACTIONS(9),
    [anon_sym_HEAD] = ACTIONS(9),
    [anon_sym_TRACE] = ACTIONS(9),
    [anon_sym_CONNECT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_SLASH_SLASH] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym_blank_line] = STATE(3),
    [sym_request_separator] = STATE(3),
    [sym_request] = STATE(3),
    [sym_method_line] = STATE(4),
    [sym_method] = STATE(29),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [aux_sym_blank_line_token1] = ACTIONS(5),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(7),
    [anon_sym_GET] = ACTIONS(9),
    [anon_sym_POST] = ACTIONS(9),
    [anon_sym_PUT] = ACTIONS(9),
    [anon_sym_DELETE] = ACTIONS(9),
    [anon_sym_PATCH] = ACTIONS(9),
    [anon_sym_OPTIONS] = ACTIONS(9),
    [anon_sym_HEAD] = ACTIONS(9),
    [anon_sym_TRACE] = ACTIONS(9),
    [anon_sym_CONNECT] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
    [anon_sym_SLASH_SLASH] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_blank_line] = STATE(3),
    [sym_request_separator] = STATE(3),
    [sym_request] = STATE(3),
    [sym_method_line] = STATE(4),
    [sym_method] = STATE(29),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [aux_sym_blank_line_token1] = ACTIONS(19),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(22),
    [anon_sym_GET] = ACTIONS(25),
    [anon_sym_POST] = ACTIONS(25),
    [anon_sym_PUT] = ACTIONS(25),
    [anon_sym_DELETE] = ACTIONS(25),
    [anon_sym_PATCH] = ACTIONS(25),
    [anon_sym_OPTIONS] = ACTIONS(25),
    [anon_sym_HEAD] = ACTIONS(25),
    [anon_sym_TRACE] = ACTIONS(25),
    [anon_sym_CONNECT] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(28),
    [anon_sym_SLASH_SLASH] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(36), 1,
      aux_sym_blank_line_token1,
    ACTIONS(41), 1,
      sym_header_name,
    STATE(11), 1,
      sym_headers,
    STATE(23), 1,
      sym_body,
    STATE(5), 2,
      sym_header,
      aux_sym_headers_repeat1,
    ACTIONS(34), 3,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
      anon_sym_SLASH_SLASH,
    ACTIONS(39), 10,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_POUND,
  [34] = 4,
    ACTIONS(41), 1,
      sym_header_name,
    STATE(7), 2,
      sym_header,
      aux_sym_headers_repeat1,
    ACTIONS(43), 4,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_SLASH_SLASH,
    ACTIONS(45), 10,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_POUND,
  [60] = 6,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      aux_sym_blank_line_token1,
    ACTIONS(53), 1,
      aux_sym_body_content_token1,
    STATE(8), 1,
      aux_sym_body_content_repeat1,
    ACTIONS(55), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(51), 11,
      anon_sym_POUND_POUND_POUND,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_SLASH_SLASH,
  [90] = 4,
    ACTIONS(61), 1,
      sym_header_name,
    STATE(7), 2,
      sym_header,
      aux_sym_headers_repeat1,
    ACTIONS(57), 4,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_SLASH_SLASH,
    ACTIONS(59), 10,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_POUND,
  [116] = 6,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 1,
      aux_sym_blank_line_token1,
    ACTIONS(71), 1,
      aux_sym_body_content_token1,
    STATE(8), 1,
      aux_sym_body_content_repeat1,
    ACTIONS(74), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
    ACTIONS(69), 11,
      anon_sym_POUND_POUND_POUND,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_SLASH_SLASH,
  [146] = 2,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 15,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      aux_sym_body_content_token1,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_SLASH_SLASH,
  [167] = 2,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 15,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      aux_sym_body_content_token1,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
      anon_sym_SLASH_SLASH,
  [188] = 4,
    ACTIONS(83), 1,
      aux_sym_blank_line_token1,
    ACTIONS(86), 1,
      anon_sym_POUND,
    STATE(22), 1,
      sym_body,
    ACTIONS(81), 12,
      ts_builtin_sym_end,
      anon_sym_POUND_POUND_POUND,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_SLASH_SLASH,
  [212] = 2,
    ACTIONS(88), 4,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_SLASH_SLASH,
    ACTIONS(90), 11,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      sym_header_name,
      anon_sym_POUND,
  [232] = 2,
    ACTIONS(92), 4,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_SLASH_SLASH,
    ACTIONS(94), 11,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      sym_header_name,
      anon_sym_POUND,
  [252] = 2,
    ACTIONS(96), 4,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_SLASH_SLASH,
    ACTIONS(98), 11,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      sym_header_name,
      anon_sym_POUND,
  [272] = 2,
    ACTIONS(100), 4,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_SLASH_SLASH,
    ACTIONS(102), 11,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      sym_header_name,
      anon_sym_POUND,
  [292] = 2,
    ACTIONS(104), 4,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_SLASH_SLASH,
    ACTIONS(106), 11,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      sym_header_name,
      anon_sym_POUND,
  [312] = 2,
    ACTIONS(110), 1,
      anon_sym_POUND,
    ACTIONS(108), 13,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_SLASH_SLASH,
  [331] = 2,
    ACTIONS(114), 1,
      anon_sym_POUND,
    ACTIONS(112), 13,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_SLASH_SLASH,
  [350] = 2,
    ACTIONS(118), 1,
      anon_sym_POUND,
    ACTIONS(116), 13,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_SLASH_SLASH,
  [369] = 2,
    ACTIONS(122), 1,
      anon_sym_POUND,
    ACTIONS(120), 13,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_SLASH_SLASH,
  [388] = 2,
    ACTIONS(126), 1,
      anon_sym_POUND,
    ACTIONS(124), 13,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_SLASH_SLASH,
  [407] = 2,
    ACTIONS(130), 1,
      anon_sym_POUND,
    ACTIONS(128), 13,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_SLASH_SLASH,
  [426] = 2,
    ACTIONS(86), 1,
      anon_sym_POUND,
    ACTIONS(81), 13,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
      anon_sym_POUND_POUND_POUND,
      anon_sym_GET,
      anon_sym_POST,
      anon_sym_PUT,
      anon_sym_DELETE,
      anon_sym_PATCH,
      anon_sym_OPTIONS,
      anon_sym_HEAD,
      anon_sym_TRACE,
      anon_sym_CONNECT,
      anon_sym_SLASH_SLASH,
  [445] = 5,
    ACTIONS(132), 1,
      aux_sym_blank_line_token1,
    ACTIONS(134), 1,
      aux_sym_body_content_token1,
    STATE(6), 1,
      aux_sym_body_content_repeat1,
    STATE(19), 1,
      sym_body_content,
    ACTIONS(55), 2,
      anon_sym_POUND,
      anon_sym_POUND_POUND,
  [462] = 3,
    ACTIONS(136), 1,
      aux_sym_blank_line_token1,
    ACTIONS(138), 1,
      aux_sym_method_line_token1,
    ACTIONS(140), 1,
      sym_header_value,
  [472] = 2,
    ACTIONS(142), 1,
      aux_sym_blank_line_token1,
    ACTIONS(144), 1,
      aux_sym_request_separator_token1,
  [479] = 2,
    ACTIONS(146), 1,
      aux_sym_blank_line_token1,
    ACTIONS(148), 1,
      aux_sym_method_line_token1,
  [486] = 1,
    ACTIONS(150), 1,
      aux_sym_blank_line_token1,
  [490] = 1,
    ACTIONS(152), 1,
      aux_sym_method_line_token1,
  [494] = 1,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
  [498] = 1,
    ACTIONS(156), 1,
      aux_sym_body_content_token2,
  [502] = 1,
    ACTIONS(158), 1,
      sym_target,
  [506] = 1,
    ACTIONS(160), 1,
      aux_sym_blank_line_token1,
  [510] = 1,
    ACTIONS(162), 1,
      sym_header_value,
  [514] = 1,
    ACTIONS(164), 1,
      aux_sym_blank_line_token1,
  [518] = 1,
    ACTIONS(166), 1,
      aux_sym_blank_line_token1,
  [522] = 1,
    ACTIONS(168), 1,
      sym_http_version,
  [526] = 1,
    ACTIONS(170), 1,
      aux_sym_blank_line_token1,
  [530] = 1,
    ACTIONS(172), 1,
      aux_sym_blank_line_token1,
  [534] = 1,
    ACTIONS(174), 1,
      anon_sym_COLON,
  [538] = 1,
    ACTIONS(176), 1,
      aux_sym_blank_line_token1,
  [542] = 1,
    ACTIONS(178), 1,
      aux_sym_method_line_token1,
  [546] = 1,
    ACTIONS(180), 1,
      aux_sym_request_separator_token1,
  [550] = 1,
    ACTIONS(182), 1,
      aux_sym_request_separator_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 34,
  [SMALL_STATE(6)] = 60,
  [SMALL_STATE(7)] = 90,
  [SMALL_STATE(8)] = 116,
  [SMALL_STATE(9)] = 146,
  [SMALL_STATE(10)] = 167,
  [SMALL_STATE(11)] = 188,
  [SMALL_STATE(12)] = 212,
  [SMALL_STATE(13)] = 232,
  [SMALL_STATE(14)] = 252,
  [SMALL_STATE(15)] = 272,
  [SMALL_STATE(16)] = 292,
  [SMALL_STATE(17)] = 312,
  [SMALL_STATE(18)] = 331,
  [SMALL_STATE(19)] = 350,
  [SMALL_STATE(20)] = 369,
  [SMALL_STATE(21)] = 388,
  [SMALL_STATE(22)] = 407,
  [SMALL_STATE(23)] = 426,
  [SMALL_STATE(24)] = 445,
  [SMALL_STATE(25)] = 462,
  [SMALL_STATE(26)] = 472,
  [SMALL_STATE(27)] = 479,
  [SMALL_STATE(28)] = 486,
  [SMALL_STATE(29)] = 490,
  [SMALL_STATE(30)] = 494,
  [SMALL_STATE(31)] = 498,
  [SMALL_STATE(32)] = 502,
  [SMALL_STATE(33)] = 506,
  [SMALL_STATE(34)] = 510,
  [SMALL_STATE(35)] = 514,
  [SMALL_STATE(36)] = 518,
  [SMALL_STATE(37)] = 522,
  [SMALL_STATE(38)] = 526,
  [SMALL_STATE(39)] = 530,
  [SMALL_STATE(40)] = 534,
  [SMALL_STATE(41)] = 538,
  [SMALL_STATE(42)] = 542,
  [SMALL_STATE(43)] = 546,
  [SMALL_STATE(44)] = 550,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 1, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_request, 1, 0, 0), SHIFT(24),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_headers, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_headers, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_content, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_content, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_headers_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_headers_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_headers_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_content_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_content_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_content_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_content_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_content_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_content_repeat1, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_content_repeat1, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_request, 2, 0, 0), SHIFT(24),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 2),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 3, 0, 2),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_line, 4, 0, 3),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_line, 4, 0, 3),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 4),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 4, 0, 4),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 5, 0, 5),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 5, 0, 5),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_line, 6, 0, 6),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_line, 6, 0, 6),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_separator, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request_separator, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_separator, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request_separator, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 1),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_line, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [154] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_http(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
